{- |
Module      :  DyckWords
Description :  An implementation of a Dyck language
Copyright   :  (c) Vasco T. Vasconcelos

The variant of a dyck word implemented is a balanced string of '<''>'
delimiters.

The context-free grammar that generates the dyck language is generated by a
single non-terminal S, and the following production:

S -> e | "[" S "]" S

(where e stands for epsilon-productions)

Example suggested by Frank Pfenning, Ankush Das, Henry DeYoung, and Andreia Mordido.

-}

module DyckWords where

type D, T : 1S
type D = +{ Lt : T;D, Dollar : Skip }
type T = +{ Lt : T;T, Gt : Skip }

-- Read from a channel; print what is read
readT : forall (a : 1S) -> (Dual T; a) -> a
readT @a c =
  case c of
    &Lt c ->
      putStr "<";
      readT (readT c)
    &Gt c ->
      putStr ">";
      c

readD : forall (a : 1S) -> (Dual D; a) -> a
readD @a c =
  case c of
    &Lt c ->
      putStr "<";
      readD (readT c)
    &Dollar c ->
      putStr "$";
      c

forwardT : forall (a : 1S) (b : 1S) -> (Dual T; a) -> (T; b) -1-> (a, b)
forwardT @a @b i o =
  case i of
    &Lt i ->
      let (i, o) = forwardT i (select Lt o) in
      forwardT i o
    &Gt i -> 
      (i, select Gt o)

-- Read from a channel and immediately write on another channel
forwardD : forall (a : 1S) (b : 1S) -> (Dual D; a) -> (D; b) -1-> (a, b)
forwardD @a @b i o =
  case i of
    &Lt i ->
      let (i, o) = forwardT i (select Lt o ) in
        forwardD i o
    &Dollar i -> 
      (i, select Dollar o)

concatT : forall (a : 1S) (b : 1S) (c : 1S) -> (Dual T; a) -> b -1-> (T; c) -1-> (a, b, c)
concatT @a @b @c i1 i2 o =
  case i1 of
    &Lt i1 ->
      let (i1, i2, o) = concatT i1 i2 (select Lt o) in
      concatT i1 i2 o
    &Gt i1 ->
      let o = select Gt o in
      (i1, i2, o)

-- Read from a channel; read from a second channel; while writing on a
-- third channel
concatD : forall (a : 1S) (b : 1S) (c : 1S) -> (Dual D; a) -> (Dual D; b) -1-> (D; c) -1-> (a, b, c)
concatD @a @b @c in1 in2 out =
  case in1 of 
    &Lt in1 ->
      let out = select Lt out in
      let (in1, in2, out) = concatT in1 in2 out in
      concatD in1 in2 out
    &Dollar in1 ->
      let (in2, out) = forwardD in2 out in
      (in1, in2, out)
    -- forwardD : forall a b -> Dual D; a -> D; b -> (a, b)

-- A few functions to write on channels
writeLtGt, writeDollar, writeLtLtGtGtLtGt, writeLtLtGtLtGtGt : (D; Close) -> Close

writeLtGt c =
  c |> select Lt |> select Gt |> select Dollar

writeDollar c = 
  c |> select Dollar

writeLtLtGtGtLtGt c =
  c |> select Lt |> select Lt 
                 |> select Gt 
    |> select Gt 
    |> select Lt 
    |> select Gt 
    |> select Dollar

writeLtLtGtLtGtGt c =
  c |> select Lt |> select Lt
                 |> select Gt 
                 |> select Lt
                 |> select Gt
    |> select Gt
    |> select Dollar

-- Putting it all together: out1 -> in1-out2 --> in2
mainForward : ()
mainForward =
  let (out1, in1) = channel @(D; Close) in
  let (out2, in2) = channel @(D; Close) in
  fork (\(_ : ()) -1-> out1 |> writeLtLtGtGtLtGt |> close);
  fork (\(_ : ()) -1-> 
      let (c1, c2) = forwardD in1 out2 in 
      wait c1;
      close c2
    );
  in2 |> readD |> wait

-- Putting it all together: (out1 | out2) --> in1-in2-out3 --> in3
main : ()
main =
  let (out1, in1) = channel @(D; Close) in
  let (out2, in2) = channel @(D; Close) in
  let (out3, in3) = channel @(D; Close) in
  fork (\(_ : ()) -1-> out1 |> writeLtLtGtGtLtGt |> close);
  fork (\(_ : ()) -1-> out2 |> writeLtLtGtLtGtGt |> close);
  fork (\(_ : ()) -1-> 
      let (c1, c2, c3) = concatD in1 in2 out3 in
      wait c1; 
      wait c2; 
      close c3
    );
  in3 |> readD |> wait
