name:       freest
version:    5.0
license:    BSD3
author:     The FreeST Team
copyright:  © 2024 FreeST Team.
synopsis:   The FreeST compiler
maintainer: The FreeST Team
homepage:   https://freest-lang.github.io/
category:   Session types

default-extensions:
  - BangPatterns
  - BlockArguments
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedRecordDot
  - PatternSynonyms
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - ViewPatterns

data-dir: data

data-files:
  - StandardLib/Prelude.fst

extra-source-files:
  - README.md

dependencies:
  - array <= 0.5.6.0
  - base >= 4.7 && < 5
  - containers >= 0.5.9
  - directory >= 1.3.2.0
  - extra >= 1.7.9
  - filepath >= 1.4.2
  - mtl >= 2.2.1
  - optparse-applicative >= 0.16.1.0
  - repline
  - sgbisim
  - transformers >= 0.5.6.2

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  exposed-modules:
    - Compiler.Bug
    - Compiler.FreeST
    - Compiler.Pipeline
    - Compiler.REPL
    - Parser.LexerUtils
    - Parser.Parser
    - Parser.Scoping
    - Parser.Unparser
    - Parser.Lexer
    - Paths_freest
    - Syntax.Base
    - Syntax.Declarations
    - Syntax.Expression
    - Syntax.Kind
    - Syntax.Module
    - Syntax.Names
    - Syntax.Type.Internal
    - Syntax.Type.Unkinded
    - Syntax.Type.Kinded
    - UI.CLI
    - UI.Error
    - Validation.Base
    - Validation.Constraint
    - Validation.Expose
    - Validation.HOTRecursion
    - Validation.Kinding
    - Validation.Normalisation
    - Validation.Substitution
    - Validation.TypeEquivalence
    - Validation.Typing

executables:
  freest:
    main:        Main.hs
    source-dirs: app
    dependencies:
      - freest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
    prog:
      main: ProgSpec.hs
      source-dirs: 
        - test/prog
      dependencies:
        - freest
        - hspec >= 2.7.1
        - HUnit >= 1.6.0.0
        - silently >= 1.2.5.1
        - process >= 1.6
      ghc-options:
        - -O2 -threaded 
        - -rtsopts 
        - -with-rtsopts=-N
    unit:
      main: UnitSpec.hs
      source-dirs:
        - test/unit
      dependencies:
        - freest
        - hspec >= 2.7.1
        - hspec-expectations >= 0.8.2
        - hspec-discover >= 2.7.1
        - split >= 0.2.3.3
